#include <iostream>
using namespace std;

int main()
{
	int top_left_corner = 201;
	int top_right_corner = 187;
	int horizontal_line = 205;
	int vertical_line = 186;
	int tee_right = 204;
	int tee_bot = 203;
	int tee_left = 185;
	int bot_left_corner = 200;
	int tee_top = 202;
	int bot_right_corner = 188;
	cout << char(top_left_corner) << char(horizontal_line) << char(horizontal_line) << char(horizontal_line) << char(horizontal_line) << char(horizontal_line) << char(horizontal_line) << char(horizontal_line) << char(horizontal_line) << char(horizontal_line) << char(horizontal_line) << char(horizontal_line) << char(horizontal_line) << char(horizontal_line) << char(horizontal_line) << char(horizontal_line) << char(horizontal_line) << char(horizontal_line) << char(horizontal_line) << char(horizontal_line) << char(horizontal_line) << char(horizontal_line) << char(horizontal_line) << char(horizontal_line) << char(horizontal_line) << char(horizontal_line) << char(horizontal_line) << char(horizontal_line) << char(horizontal_line) << char(horizontal_line) << char(horizontal_line) << char(horizontal_line) << char(horizontal_line) << char(horizontal_line) << char(horizontal_line) << char(horizontal_line) << char(horizontal_line) << char(horizontal_line) << char(horizontal_line) << char(horizontal_line) << char(horizontal_line) << char(horizontal_line) << char(horizontal_line) << char(horizontal_line) << char(horizontal_line) << char(horizontal_line) << char(horizontal_line) << char(horizontal_line) << char(horizontal_line) << char(horizontal_line) << char(horizontal_line) << char(horizontal_line) << char(horizontal_line) << char(horizontal_line) << char(horizontal_line) << char(horizontal_line) << char(horizontal_line) << char(horizontal_line) << char(horizontal_line) << char(horizontal_line) << char(horizontal_line) << char(horizontal_line) << char(horizontal_line) << char(horizontal_line) << char(horizontal_line) << char(horizontal_line) << char(horizontal_line) << char(horizontal_line) << char(horizontal_line) << char(horizontal_line) << char(horizontal_line) << char(horizontal_line) << char(horizontal_line) << char(horizontal_line) << char(horizontal_line) << char(horizontal_line) << char(horizontal_line) << char(horizontal_line) << char(horizontal_line) << char(horizontal_line) << char(horizontal_line) << char(horizontal_line) << char(horizontal_line) << char(horizontal_line) << char(horizontal_line) << char(top_right_corner) << endl;
	cout << char(vertical_line) << "                                  " << "Vremena goda" << "                                      " << char(vertical_line) << endl;
	cout << char(tee_right) << char(horizontal_line) << char(horizontal_line) << char(horizontal_line) << char(horizontal_line) << char(horizontal_line) << char(horizontal_line) << char(horizontal_line) << char(horizontal_line) << char(horizontal_line) << char(horizontal_line) << char(horizontal_line) << char(horizontal_line) << char(horizontal_line) << char(horizontal_line) << char(horizontal_line) << char(horizontal_line) << char(horizontal_line) << char(horizontal_line) << char(horizontal_line) << char(horizontal_line) << char(horizontal_line) << char(tee_bot) << char(horizontal_line) << char(horizontal_line) << char(horizontal_line) << char(horizontal_line) << char(horizontal_line) << char(horizontal_line) << char(horizontal_line) << char(horizontal_line) << char(horizontal_line) << char(horizontal_line) << char(horizontal_line) << char(horizontal_line) << char(horizontal_line) << char(horizontal_line) << char(horizontal_line) << char(horizontal_line) << char(horizontal_line) << char(horizontal_line) << char(horizontal_line) << char(tee_bot) << char(horizontal_line) << char(horizontal_line) << char(horizontal_line) << char(horizontal_line) << char(horizontal_line) << char(horizontal_line) << char(horizontal_line) << char(horizontal_line) << char(horizontal_line) << char(horizontal_line) << char(horizontal_line) << char(horizontal_line) << char(horizontal_line) << char(horizontal_line) << char(horizontal_line) << char(horizontal_line) << char(horizontal_line) << char(horizontal_line) << char(horizontal_line) << char(horizontal_line) << char(horizontal_line) << char(tee_bot) << char(horizontal_line) << char(horizontal_line) << char(horizontal_line) << char(horizontal_line) << char(horizontal_line) << char(horizontal_line) << char(horizontal_line) << char(horizontal_line) << char(horizontal_line) << char(horizontal_line) << char(horizontal_line) << char(horizontal_line) << char(horizontal_line) << char(horizontal_line) << char(horizontal_line) << char(horizontal_line) << char(horizontal_line) << char(horizontal_line) << char(horizontal_line) << char(horizontal_line)<< char(tee_left) << endl;
	cout << char(vertical_line) << "       Zima          " << char(vertical_line) << "        Vesna      " << char(vertical_line) << "         Leto        " << char(vertical_line) << "       Osen         " << char(vertical_line) << endl;
	cout << char(bot_left_corner) << char(horizontal_line) << char(horizontal_line) << char(horizontal_line) << char(horizontal_line) << char(horizontal_line) << char(horizontal_line) << char(horizontal_line) << char(horizontal_line) << char(horizontal_line) << char(horizontal_line) << char(horizontal_line) << char(horizontal_line) << char(horizontal_line) << char(horizontal_line) << char(horizontal_line) << char(horizontal_line) << char(horizontal_line) << char(horizontal_line) << char(horizontal_line) << char(horizontal_line) << char(horizontal_line) << char(tee_top) << char(horizontal_line) << char(horizontal_line) << char(horizontal_line) << char(horizontal_line) << char(horizontal_line) << char(horizontal_line) << char(horizontal_line) << char(horizontal_line) << char(horizontal_line) << char(horizontal_line) << char(horizontal_line) << char(horizontal_line) << char(horizontal_line) << char(horizontal_line) << char(horizontal_line) << char(horizontal_line) << char(horizontal_line) << char(horizontal_line) << char(horizontal_line) << char(tee_top) << char(horizontal_line) << char(horizontal_line) << char(horizontal_line) << char(horizontal_line) << char(horizontal_line) << char(horizontal_line) << char(horizontal_line) << char(horizontal_line) << char(horizontal_line) << char(horizontal_line) << char(horizontal_line) << char(horizontal_line) << char(horizontal_line) << char(horizontal_line) << char(horizontal_line) << char(horizontal_line) << char(horizontal_line) << char(horizontal_line) << char(horizontal_line) << char(horizontal_line) << char(horizontal_line) << char(tee_top) << char(horizontal_line) << char(horizontal_line) << char(horizontal_line) << char(horizontal_line) << char(horizontal_line) << char(horizontal_line) << char(horizontal_line) << char(horizontal_line) << char(horizontal_line) << char(horizontal_line) << char(horizontal_line) << char(horizontal_line) << char(horizontal_line) << char(horizontal_line) << char(horizontal_line) << char(horizontal_line) << char(horizontal_line) << char(horizontal_line) << char(horizontal_line) << char(horizontal_line) << char(bot_right_corner) << endl;
	return 0;
}